#credentials for api
API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
API_SECRET_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
